language: python
dist: trusty
notifications:
  email: false
python:
  - 3.6
before_install:
  - pip install flake8
  - flake8 dashboard
  - flake8 tests
install:
  - pip install -r requirements.txt
  - npm install -g eslint stylelint
script:
  - pytest
  - eslint 'dashboard/static/js/*.js'
  - stylelint 'dashboard/static/css/*.scss'
