# This is an appspec.yml template file for use with AWS CodeDeploy.

version: 0.0

os: linux

files:
  - source: /
    destination: /home/ec2-user/app/

hooks:
  BeforeInstall:
    - location: scripts/prep-deploy.sh
      timeout: 120
      runas: root

  AfterInstall:
    - location: scripts/build-environment.sh
      timeout: 600
      runas: root

  ApplicationStart:
    - location: scripts/post-deploy.sh
      timeout: 120
      runas: root

  ValidateService:
    - location: scripts/validate-deploy.sh
      timeout: 120
      runas: root
