version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Creating archive of python code.
  post_build:
    commands:
      - echo Build completed on `date`
      - aws deploy push --application-name sso-dashboard-dev --s3-location s3://$S3_BUCKET/sso-dashboard-app.zip --ignore-hidden-files
artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: yes
