version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Creating archive of python code.
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
