version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Creating archive of python code.
      - echo installing ansible-container
      - pip install install ansible-container[docker]
      - ansible-container build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
