version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Creating archive of python code.
  post_build:
    commands:
      - echo Build completed on `date`
      - aws deploy push --region us-west-2 --application-name sso-dashboard-dev --s3-location s3://sso-dashboard.deploy-dev/sso-dashboard-app.zip --ignore-hidden-files --source .
artifacts:
  files:
    - 'ansible/**'
    - 'dashboard/**'
    - 'appspec.yml'
  base-directory: '.'
