version: "2"
settings:
  volumes:
    ../:/dashboard
services:
  web:
    from: centos:7
    expose:
      - "8000/tcp"
    ports:
      - "80:80"
      - "8000:8000"
    links:
      - redis:redis
    working_dir: '/sso-dashboard'
    roles:
      - dashboard
    command: ['/usr/bin/dumb-init', '/usr/bin/start.sh']
  redis:
    from: redis
    expose:
      - "6379/tcp"
    ports:
      - "6379:6379"
    command: ['redis-server']
registries: {}
